/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.convertidor;

/**
 *
 * @author Acer
 */
public class Convertidor extends javax.swing.JFrame {

    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRbc = new javax.swing.JTextField();
        txtRab = new javax.swing.JTextField();
        txtRac = new javax.swing.JTextField();
        lblDelta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        txtRbc.setDropMode(javax.swing.DropMode.INSERT);
        txtRbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRbcActionPerformed(evt);
            }
        });
        getContentPane().add(txtRbc);
        txtRbc.setBounds(160, 130, 70, 40);

        txtRab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRabActionPerformed(evt);
            }
        });
        getContentPane().add(txtRab);
        txtRab.setBounds(110, 200, 70, 40);
        getContentPane().add(txtRac);
        txtRac.setBounds(60, 130, 70, 40);

        lblDelta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/convertidor/imagenes/Sin título-2.png"))); // NOI18N
        lblDelta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDelta.setFocusable(false);
        getContentPane().add(lblDelta);
        lblDelta.setBounds(20, 30, 247, 246);
        lblDelta.getAccessibleContext().setAccessibleParent(txtRbc);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRbcActionPerformed

    private void txtRabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDelta;
    private javax.swing.JTextField txtRab;
    private javax.swing.JTextField txtRac;
    private javax.swing.JTextField txtRbc;
    // End of variables declaration//GEN-END:variables
}
